apiVersion: v1
kind: ConfigMap
metadata:
  name: servicebus-ingester-go-config
  namespace: experiment
data:
  HEALTH_PORT: "8080"

  DB_USER: "ingestionservicebusingester"
  DB_PORT: "5432"
  DB_DATABASE: "vce_experiment_ingestion_servicebusingester"
  DB_SCHEMA: "ingestionservicebusingester"
  DB_SSL_MODE: "require"
  DB_MAX_CONNS: "20"
  DB_CONNECTION_IDLE_TIME_MINUTES: "5"
  DB_CONNECTION_LIFE_TIME_MINUTES: "30"

  SB_CONSUMER_COUNT: "20"
  SB_BATCH_SIZE: "100"
  SB_SEND_TOPIC: "sb-loadtest-send"

  SB_MACHINE_LOCATION_TOPIC: "sb-loadtest-listen"
  SB_MACHINE_LOCATION_SUBSCRIPTION: "go-ingester"
  SB_MACHINE_LOCATION_STRATEGY: "batch"

  SB_USER_UPDATED_TOPIC: "sb-loadtest-listen"
  SB_USER_UPDATED_SUBSCRIPTION: "go-ingester"
  SB_USER_UPDATED_STRATEGY: "single"
