// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package queries

import (
	"context"
)

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, message_id, event_type, source, body, created_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.EventType,
		&i.Source,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (message_id, event_type, source, body)
VALUES ($1, $2, $3, $4)
`

type InsertMessageParams struct {
	MessageID string `json:"message_id"`
	EventType string `json:"event_type"`
	Source    string `json:"source"`
	Body      []byte `json:"body"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.MessageID,
		arg.EventType,
		arg.Source,
		arg.Body,
	)
	return err
}

const listMessagesByEventType = `-- name: ListMessagesByEventType :many
SELECT id, message_id, event_type, source, body, created_at FROM messages WHERE event_type = $1 ORDER BY created_at DESC LIMIT $2
`

type ListMessagesByEventTypeParams struct {
	EventType string `json:"event_type"`
	MsgLimit  int32  `json:"msg_limit"`
}

func (q *Queries) ListMessagesByEventType(ctx context.Context, arg ListMessagesByEventTypeParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByEventType, arg.EventType, arg.MsgLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.EventType,
			&i.Source,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
