// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        int64              `json:"id"`
	MessageID string             `json:"message_id"`
	EventType string             `json:"event_type"`
	Source    string             `json:"source"`
	Body      []byte             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
