apiVersion: v1
kind: ConfigMap
metadata:
  name: servicebus-ingester-config
  namespace: experiment
data:
  CONSUMER_COUNT: "10"
  BATCH_SIZE: "20"
  HEALTH_PORT: "8080"
  SERVICEBUS_TOPIC: "sb-loadtest-listen"
  SERVICEBUS_SUBSCRIPTION: "go-ingester"
  DATABASE_SCHEMA: "ingestionservicebusingester"
  SERVICEBUS_SEND_TOPIC: "sb-loadtest-send"
